imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:
        fallback: ru
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: false
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        fb_app_id: %fb_app_id%
        disqus_shortname: %disqus_shortname%
        admin_email: %admin_email%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        mappings:
            FOSUserBundle: ~
            GeekPartyBundle: ~
            PrismPollBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: public
    user_class: Geek\PartyBundle\Entity\User

stfalcon_tinymce:
        tinymce_jquery: true
        selector: ".tinymce"
        #base_url: "http://yourdomain.com/" # this parameter may be included if you need to override the assets_base_urls for your template engine (to override a CDN base url)
        # Get current language from the parameters.ini
        language: %locale%
        theme:
            # Simple theme: same as default theme
            simple: ~
            comment:
                plugins:
                 - "advlist autolink lists link image charmap anchor pagebreak"
                 - "wordcount visualblocks visualchars code"
                 - "insertdatetime media nonbreaking save table contextmenu directionality"
                 - "paste textcolor"
                toolbar1: "undo redo | bold italic underline strikethrough | alignleft aligncenter alignright | bullist numlist outdent indent | code"
                menubar: false
                statusbar: false
            # Advanced theme with almost all enabled plugins
            advanced:
                 plugins:
                     - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                     - "searchreplace wordcount visualblocks visualchars code fullscreen"
                     - "insertdatetime media nonbreaking save table contextmenu directionality"
                     - "emoticons paste textcolor"
                 toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
                 toolbar2: "print preview media | forecolor backcolor emoticons | "
                 image_advtab: true
                 relative_urls: false
            admin:
                 plugins:
                     - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                     - "searchreplace wordcount visualblocks visualchars code fullscreen"
                     - "insertdatetime media nonbreaking save table contextmenu directionality"
                     - "emoticons paste textcolor filemanager"
                 toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
                 toolbar2: "print preview media | forecolor backcolor emoticons | "
                 image_advtab: true
                 relative_urls: false
                 external_filemanager_path: "/image_upload/filemanager/"
                 filemanager_title: "Файловый менеджер"
                 external_plugins: { "filemanager" : "/filemanager/plugin.min.js"}

exercise_html_purifier:
    default:
        HTML.Allowed: >
          p[style],em,strong,ul,ol,li,a[href],img[src],span[style],sup,sub,table,tbody,tr,td,th,iframe[src],
          h1,h2,h3,h4,h5,br
        HTML.SafeIframe: true
        URI.SafeIframeRegexp: $(youtube.com/embed|w.soundcloud.com)$

hwi_oauth:
    connect:
        account_connector: my_user_provider
    firewall_name: public
    resource_owners:
        facebook:
            type:                facebook
            client_id:           %fb_app_id%
            client_secret:       %fb_secret%
            scope:               email
            options:
                display: page
        vkontakte:
            type:                vkontakte
            client_id:           %vk_app_id%
            client_secret:       %vk_app_secret%
            scope:               email
    fosub:
        username_iterations: 30
        properties:
            facebook: facebookId
            vkontakte: vkontakteId

services:
    my_user_provider:
        class: Geek\PartyBundle\Security\User\Provider\FOSUBUserProvider
        arguments:
            - @fos_user.user_manager
            - { facebook: facebookId, vkontakte: vkontakteId }
    geek.twig.twig_extension:
        class: Geek\PartyBundle\Twig\GeekExtension
        arguments: [ @security.context, @kernel ]
        tags:
            - { name: twig.extension }
    work.repo:
        class: Geek\PartyBundle\Entity\Repository\WorkRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ 'GeekPartyBundle:Work' ]
        calls:
            - ['setRootDir', [ %kernel.root_dir% ]]

lexik_maintenance:
    driver:
        class: '\Lexik\Bundle\MaintenanceBundle\Drivers\FileDriver'                # class for file driver
        options: {file_path: %kernel.root_dir%/cache/lock}                         # file_path is the complete path for create the file