imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        fb_app_id: %fb_app_id%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        mappings:
            FOSUserBundle: ~
            GeekPartyBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: public
    user_class: Geek\PartyBundle\Entity\User

stfalcon_tinymce:
        include_jquery: true
        tinymce_jquery: true
        selector: ".tinymce"
        #base_url: "http://yourdomain.com/" # this parameter may be included if you need to override the assets_base_urls for your template engine (to override a CDN base url)
        # Get current language from the parameters.ini
        language: %locale%
        theme:
            # Simple theme: same as default theme
            simple: ~
            # Advanced theme with almost all enabled plugins
            advanced:
                 plugins:
                     - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                     - "searchreplace wordcount visualblocks visualchars code fullscreen"
                     - "insertdatetime media nonbreaking save table contextmenu directionality"
                     - "emoticons paste textcolor"
                 toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
                 toolbar2: "print preview media | forecolor backcolor emoticons | "
                 image_advtab: true

exercise_html_purifier:
    default:
        HTML.Allowed: >
          p[style],em,strong,ul,ol,li,a[href],img[src],span[style],sup,sub,table,tbody,tr,td,th,iframe[src],
          h1,h2,h3,h4,h5
        HTML.SafeIframe: true
        URI.SafeIframeRegexp: $youtube.com/embed/$

hwi_oauth:
    connect:
        account_connector: my_user_provider
    firewall_name: public
    resource_owners:
        facebook:
            type:                facebook
            client_id:           %fb_app_id%
            client_secret:       %fb_secret%
            scope:               email
    fosub:
        username_iterations: 30
        properties:
            facebook: facebookId

services:
    my_user_provider:
        class: Geek\PartyBundle\Security\User\Provider\FOSUBUserProvider
        arguments:
            - @fos_user.user_manager
            - { facebook: facebookId }
    geek.twig.twig_extension:
        class: Geek\PartyBundle\Twig\GeekExtension
        arguments: [ @security.context, @kernel ]
        tags:
            - { name: twig.extension }