# Main
geek_index:
    pattern:  /
    defaults: { _controller: GeekPartyBundle:Main:index }
geek_about:
    pattern:  /about
    defaults: { _controller: GeekPartyBundle:Main:about }
admin:
    pattern: /admin
    defaults: {_controller:GeekPartyBundle:Main:admin}
github_hook:
  pattern: /github_hook
  defaults: {_controller:GeekPartyBundle:GitHub:hook}

escaped_percent_redirect:
    path: /browse/GDP%231/{work}
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: geek_browse_work
        party: 'GDP#1'
        work: work

# News article
article:
    pattern: /article/{id}/{from}
    defaults: { _controller: GeekPartyBundle:Article:action, action: show, from: 0 }

# Browse
geek_browse:
    pattern:  /browse/{party}
    defaults: { _controller: GeekPartyBundle:Browse:party, party: latest }
geek_browse_work:
    pattern:  /browse/{party}/{work}/{from}
    defaults: { _controller: GeekPartyBundle:Browse:work, party: latest, from: 0 }
geek_vote:
    pattern:  /vote
    defaults: { _controller: GeekPartyBundle:Browse:vote }

# Admin
admin_parties:
    pattern: /admin/party/{action}/{id}
    defaults: { _controller: GeekPartyBundle:Party:action, action: index, id: -1 }
    requirements:
        action: edit|index|update|delete
admin_works:
    pattern: /admin/work/{action}/{id}
    defaults: { _controller: GeekPartyBundle:Work:action, action: index, id: -1 }
    requirements:
        action: edit|index|update|delete
admin_text:
    pattern: /admin/text/{action}/{id}
    defaults: { _controller: GeekPartyBundle:Text:action, action: index, id: -1 }
    requirements:
        action: edit|index|update|delete
_edit_article:
    pattern: /article_edit/{action}/{id}
    defaults: { _controller: GeekPartyBundle:Article:action, action: index, id: -1 }
    requirements:
        action: edit|index|update|delete|vote

# Themes adding & voting
party_themes:
    resource: "@GeekPartyBundle/Controller/PartyThemeController.php"
    type:     annotation
    prefix:   /party

# Upload & edit project
_edit_prject:
    resource: "@GeekPartyBundle/Controller/ProjectController.php"
    type:     annotation
    prefix:   /edit

# User
_user:
    resource: "@GeekPartyBundle/Controller/UserController.php"
    type:     annotation
    prefix:   /user

# Comments
_comment:
    resource: "@GeekPartyBundle/Controller/CommentController.php"
    type:     annotation
    prefix:   /comment

# Auth & security
_auth:
    resource: routing_security.yml

PrismPollBundle_backend:
    prefix: /poll/backend
    resource: "@PrismPollBundle/Resources/config/routing/backend.yml"

PrismPollBundle_frontend:
    prefix: /poll
    resource: "@PrismPollBundle/Resources/config/routing/frontend.yml"

