# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
geek_index:
    pattern:  /
    defaults: { _controller: GeekPartyBundle:Main:index }

geek_people:
    pattern:  /people
    defaults: { _controller: GeekPartyBundle:Main:people }

geek_about:
    pattern:  /about
    defaults: { _controller: GeekPartyBundle:Main:about }

geek_default_works:
    pattern:  /works
    defaults: { _controller: GeekPartyBundle:Main:works, party: gp2 }

geek_party_works:
    pattern:  /works/{party}
    defaults: { _controller: GeekPartyBundle:Main:works }

geek_work:
    pattern:  /works/{party}/{work}
    defaults: { _controller: GeekPartyBundle:Main:workPage }

geek_test:
    pattern:  /test
    defaults: { _controller: GeekPartyBundle:Main:test }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
