fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_security_register:
    prefix: /register
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"

fos_facebook_channel:
    resource: "@FOSFacebookBundle/Resources/config/routing.xml"

_security_check:
    pattern:  /login_check
    defaults: { _controller: GeekPartyBundle:Auth:check }
_security_logout:
    pattern:  /logout
    defaults: { _controller: GeekPartyBundle:Auth:logout }