fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

# app/config/routing.yml
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login
facebook_login:
    pattern: /login/check-facebook
vkontakte_login:
    pattern: /login/check-vkontakte