# Main
geek_index:
    pattern:  /
    defaults: { _controller: GeekPartyBundle:Main:index }
geek_about:
    pattern:  /about
    defaults: { _controller: GeekPartyBundle:Main:about }
admin:
    pattern: /admin
    defaults: {_controller:GeekPartyBundle:Main:admin}
github_hook:
  pattern: /github_hook
  defaults: {_controller:GeekPartyBundle:GitHub:hook}

_edit_nwq_article:
    pattern: /article/edit
    defaults: { _controller: GeekPartyBundle:Article:action, action: edit, id: -1 }

# News article
article:
    pattern: /article/{id}
    defaults: { _controller: GeekPartyBundle:Article:action, action: show }

# Browse
geek_browse:
    pattern:  /browse/{party}
    defaults: { _controller: GeekPartyBundle:Browse:party, party: latest }
geek_browse_work:
    pattern:  /browse/{party}/{work}
    defaults: { _controller: GeekPartyBundle:Browse:work, party: latest }

# Admin
admin_parties:
    pattern: /admin/party/{action}/{id}
    defaults: { _controller: GeekPartyBundle:Party:action, action: index, id: -1 }
    requirements:
        action: edit|index|update|delete
admin_works:
    pattern: /admin/work/{action}/{id}
    defaults: { _controller: GeekPartyBundle:Work:action, action: index, id: -1 }
    requirements:
        action: edit|index|update|delete
admin_text:
    pattern: /admin/text/{action}/{id}
    defaults: { _controller: GeekPartyBundle:Text:action, action: index, id: -1 }
    requirements:
        action: edit|index|update|delete
_edit_article:
    pattern: /article/{action}/{id}
    defaults: { _controller: GeekPartyBundle:Article:action, action: index, id: -1 }
    requirements:
        action: edit|index|update|delete|vote


# Upload & edit project
_edit_prject:
    resource: "@GeekPartyBundle/Controller/ProjectController.php"
    type:     annotation
    prefix:   /edit

# Auth & security
_auth:
    resource: routing_security.yml

PrismPollBundle_backend:
    prefix: /poll/backend
    resource: "@PrismPollBundle/Resources/config/routing/backend.yml"

PrismPollBundle_frontend:
    prefix: /poll
    resource: "@PrismPollBundle/Resources/config/routing/frontend.yml"