jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [fos_user_bundle]
        fos_user_bundle:
            id: fos_user.user_provider.username

    firewalls:
        public:
            anonymous: ~
            logout: true
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    vkontakte:           "/login/check-vkontakte"
                login_path:        /login
                use_forward:       false
                failure_path:      /login
                default_target_path: /user/after_login
                oauth_user_provider:
                    service: my_user_provider
            form_login:
                use_referer: true
                failure_path: geek_login_failure

    access_control:
        - { path: ^/(login|register|resetting), role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(edit|vote|comment|article_edit), role: IS_AUTHENTICATED_FULLY }
        - { path: ^/(admin/|poll|image_upload|filemanager), role: ROLE_ADMIN }
