PrismPollBundle_backend_poll_list:
    pattern:  /list
    defaults: { _controller: PrismPollBundle:Backend\Poll:list }

PrismPollBundle_backend_poll_edit:
    pattern:  /edit/{pollId}
    defaults: { _controller: PrismPollBundle:Backend\Poll:edit, pollId: 0 }

PrismPollBundle_backend_poll_delete:
    pattern:  /delete/{pollId}
    defaults: { _controller: PrismPollBundle:Backend\Poll:delete }